# Generated by Django 4.0 on 2022-10-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID Пользователя')),
                ('short_id', models.CharField(max_length=7, unique=True, verbose_name='Короткий ID Пользователя')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Username пользователя')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия пользователя')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество пользователя')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона пользователя в международном формате')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Адрес электронной почты пользователя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Пользователь активен?')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created_at'],
            },
        ),
    ]
