# Generated by Django 4.0 on 2022-10-28 21:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_showuserprofile_socialnetwork_remove_user_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showuserprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID информации о приватности'),
        ),
        migrations.AlterField(
            model_name='showuserprofile',
            name='show_email',
            field=models.BooleanField(default=False, verbose_name='Показывать осн. почту?'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID соц. сети'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID информации о пользователе'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.user', verbose_name='Пользователь'),
        ),
    ]
