# Generated by Django 4.0 on 2022-10-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_showuserprofile_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialnetwork',
            name='confirmed',
        ),
    ]
