# Generated by Django 4.0 on 2022-10-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_socialnetwork_confirmed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShowUserProfile',
            new_name='ProfileSettings',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='show_info',
            new_name='profile_settings',
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='network_type',
            field=models.CharField(choices=[('VK', 'Вконтакте'), ('TG', 'Telegram'), ('IG', 'Instagram'), ('FB', 'Facebook'), ('YT', 'YouTube'), ('TW', 'Twitter'), ('LI', 'LinkedIn'), ('GG', 'Google')], max_length=5, verbose_name='Тип соц.сети'),
        ),
    ]
