# Generated by Django 4.0 on 2022-10-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_showuserprofile_profilesettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesettings',
            name='show_social_networks',
            field=models.BooleanField(default=False, verbose_name='Показывать соц. сети?'),
        ),
    ]
