# Generated by Django 4.0 on 2022-10-29 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profilesettings_show_social_networks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='social_networks',
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='user_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='Профиль пользователя'),
            preserve_default=False,
        ),
    ]
