# Generated by Django 4.0 on 2022-10-29 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_userprofile_social_networks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='network_type',
            field=models.CharField(choices=[('Вконтакте', 'Вконтакте'), ('Telegram', 'Telegram'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('YouTube', 'YouTube'), ('Twitter', 'Twitter'), ('LinkedIn', 'LinkedIn'), ('Google', 'Google')], max_length=10, verbose_name='Тип соц.сети'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='users.userprofile', verbose_name='Профиль пользователя'),
        ),
    ]
