# Generated by Django 4.0 on 2022-10-29 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_socialnetwork_network_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialnetwork',
            name='show',
        ),
    ]
