# Generated by Django 4.0 on 2022-10-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_skill_userprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус человека'),
        ),
    ]
