# Generated by Django 4.0 on 2022-10-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Пользователь верифицирован?'),
        ),
    ]
