# Generated by Django 4.0 on 2022-10-31 23:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesettings',
            name='show_interests',
            field=models.BooleanField(default=False, verbose_name='Показывать интересы?'),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='show_skills',
            field=models.BooleanField(default=False, verbose_name='Показывать навыки?'),
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID интереса')),
                ('name', models.CharField(max_length=255, verbose_name='Название интереса')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.interest', verbose_name='Родительский интерес')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='users.Interest', verbose_name='Интересы пользователя'),
        ),
    ]
