# Generated by Django 4.0 on 2022-10-31 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profilesettings_show_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Вес интереса'),
        ),
    ]
