# Generated by Django 4.0 on 2022-11-01 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_interest_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesettings',
            name='can_be_invited',
            field=models.BooleanField(default=True, verbose_name='Может ли быть приглашен в группу?'),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='show_biography',
            field=models.BooleanField(default=True, verbose_name='Показывать биографию?'),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='show_interests',
            field=models.BooleanField(default=True, verbose_name='Показывать интересы?'),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='show_sex',
            field=models.BooleanField(default=True, verbose_name='Показывать пол?'),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='show_skills',
            field=models.BooleanField(default=True, verbose_name='Показывать навыки?'),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='show_social_networks',
            field=models.BooleanField(default=True, verbose_name='Показывать соц. сети?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.profilesettings', verbose_name='Какие поля показывать?'),
        ),
    ]
