# Generated by Django 4.0 on 2022-11-02 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_interest_options_alter_profilesettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilesettings',
            options={'verbose_name': 'Настройки профиля', 'verbose_name_plural': 'Настройки профиля'},
        ),
        migrations.AddField(
            model_name='skill',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.skill', verbose_name='Родительский навык'),
        ),
        migrations.AddField(
            model_name='skill',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Вес навыка'),
        ),
    ]
