# Generated by Django 4.0 on 2022-11-02 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_chatnotification_is_read'),
        ('users', '0021_alter_profilesettings_options_skill_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest', to='chats.chat', verbose_name='Чат'),
        ),
    ]
