# Generated by Django 4.0 on 2022-11-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_country_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddinfo',
            name='education_level',
            field=models.IntegerField(choices=[(0, 'Среднее общее образование (9 классов)'), (1, 'Среднее полное образование (11 классов)'), (2, 'Среднее профессиональное образование'), (3, 'Незаконченное высшее образование'), (4, 'Бакалавриат'), (5, 'Специалитет'), (6, 'Магистратура'), (7, 'Аспирантура'), (8, 'Докторантура')], default=0, verbose_name='Уровень образования'),
        ),
    ]
