# Generated by Django 4.0 on 2022-11-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_useraddinfo_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddinfo',
            name='education_level',
            field=models.IntegerField(choices=[(0, 'Среднее общее образование (9 классов)'), (1, 'Среднее полное образование (11 классов)'), (2, 'Среднее профессиональное образование'), (3, 'Незаконченное высшее образование'), (4, 'Бакалавриат'), (5, 'Специалитет'), (6, 'Магистратура'), (7, 'Аспирантура'), (8, 'Докторантура')], default=4, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='useraddinfo',
            name='employment',
            field=models.IntegerField(blank=True, choices=[(0, 'Полная занятость'), (1, 'Частичная занятость'), (2, 'Проектная работа'), (3, 'Волонтерство'), (4, 'Стажировка'), (5, 'Свой бизнес'), (6, 'Самозанятый'), (7, 'Безработный')], default=0, null=True, verbose_name='Занятость'),
        ),
    ]
