# Generated by Django 4.0 on 2022-11-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_useraddinfo_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_thumbnail',
            field=models.URLField(blank=True, max_length=2048, null=True, unique=True, verbose_name='Миниатюра аватара'),
        ),
    ]
