# Generated by Django 4.0 on 2022-11-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesettings',
            name='show_citizenship',
            field=models.BooleanField(default=True, verbose_name='Показывать гражданство?'),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='show_company_information',
            field=models.BooleanField(default=True, verbose_name='Показывать информацию о компании?'),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='show_education',
            field=models.BooleanField(default=True, verbose_name='Показывать образование?'),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='show_employment',
            field=models.BooleanField(default=True, verbose_name='Показывать статус трудоустройства?'),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='show_hack_experience',
            field=models.BooleanField(default=True, verbose_name='Показывать опыт участия в хакатонах?'),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='show_iar_information',
            field=models.BooleanField(default=True, verbose_name='Показывать информацию о РИД?'),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='show_professional_skills',
            field=models.BooleanField(default=True, verbose_name='Показывать профессиональные навыки?'),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='show_team_roles',
            field=models.BooleanField(default=True, verbose_name='Показывать роли в командах?'),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='show_work_experience',
            field=models.BooleanField(default=True, verbose_name='Показывать опыт работы?'),
        ),
    ]
