# Generated by Django 4.0 on 2022-11-04 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_profilesettings_show_citizenship_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilesettings',
            old_name='show_professional_skills',
            new_name='show_professional_experience',
        ),
    ]
