# Generated by Django 4.0 on 2022-11-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_rename_show_professional_skills_profilesettings_show_professional_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(default='RUS', max_length=255, verbose_name='Код страны'),
            preserve_default=False,
        ),
    ]
