# Generated by Django 4.0 on 2022-10-30 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0016_user_is_verified'),
        ('ideas', '0005_alter_ideacomment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID Пользователя')),
                ('name', models.CharField(max_length=255, verbose_name='Название команды')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание команды')),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ideas.idea', verbose_name='Идея')),
                ('members', models.ManyToManyField(related_name='teams', to='users.User', verbose_name='Участники команды')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to='users.user', verbose_name='Лидер команды')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID Заявки')),
                ('request_type', models.PositiveSmallIntegerField(choices=[(0, 'Входящий запрос'), (1, 'Исходящий запрос')], verbose_name='Тип запроса')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Заявка принята?')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_requests', to='teams.team', verbose_name='Команда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
