# Generated by Django 4.0 on 2022-10-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_id_alter_teamrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название команды'),
        ),
    ]
