# Generated by Django 4.0 on 2022-10-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrequest',
            name='cover_letter',
            field=models.TextField(blank=True, null=True, verbose_name='Сопроводительное письмо'),
        ),
    ]
