# Generated by Django 4.0 on 2022-10-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_teamrequest_cover_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamrequest',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='request_status',
            field=models.IntegerField(choices=[(0, 'Подана'), (1, 'Принята'), (2, 'Отклонена')], default=0, verbose_name='Статус запроса'),
        ),
    ]
