# Generated by Django 4.0 on 2022-10-31 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_teamrequest_is_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_looking_for_members',
            field=models.BooleanField(default=False, verbose_name='Ищет ли команда участников?'),
        ),
    ]
