# Generated by Django 4.0 on 2022-11-01 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('teams', '0009_remove_team_vk_chat_id_remove_team_vk_chat_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='chat',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='chats.chat', verbose_name='Чат команды'),
            preserve_default=False,
        ),
    ]
