# Generated by Django 4.0 on 2022-11-01 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chat_chat_type'),
        ('teams', '0011_alter_team_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_chat', to='chats.chat', verbose_name='Чат команды'),
        ),
    ]
