# Generated by Django 4.0 on 2022-11-04 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_useraddinfo_education_level_and_more'),
        ('teams', '0012_alter_team_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrequest',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_role_requests', to='users.teamrole', verbose_name='Роль пользователя'),
            preserve_default=False,
        ),
    ]
