# Generated by Django 4.0 on 2022-11-04 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_useraddinfo_education_level_and_more'),
        ('teams', '0013_teamrequest_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Дата вступления')),
                ('membership_requester', models.IntegerField(choices=[(0, 'Пользователь'), (1, 'Команда')], verbose_name='Инициатор членства')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teamrole', verbose_name='Роль в команде')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Команда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Пользователь')),
            ],
        ),
    ]
