# Generated by Django 4.0 on 2022-11-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
    ]
