# Generated by Django 4.0 on 2022-11-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_useraddinfo_education_level_and_more'),
        ('teams', '0015_remove_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', through='teams.Membership', to='users.User', verbose_name='Участники команды'),
        ),
    ]
