# Generated by Django 4.0 on 2022-11-05 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_country_country_code'),
        ('teams', '0018_alter_membership_options_membership_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('amount', models.IntegerField(default=1, verbose_name='Количество людей с данной ролью')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teamrole', verbose_name='Роль в команде')),
            ],
            options={
                'verbose_name': 'Требуемые роли в команде',
                'verbose_name_plural': 'Требуемые роли в команде',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='required_roles',
            field=models.ManyToManyField(related_name='required_roles', through='teams.RequiredMembers', to='users.TeamRole', verbose_name='Необходимые участники'),
        ),
        migrations.AddField(
            model_name='requiredmembers',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Команда'),
        ),
        migrations.AddConstraint(
            model_name='requiredmembers',
            constraint=models.UniqueConstraint(fields=('role', 'team'), name='team_role_unique'),
        ),
    ]
