# Generated by Django 4.0 on 2022-11-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0021_alter_team_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='is_looking_for_members',
            field=models.BooleanField(default=True, verbose_name='Ищет ли команда участников?'),
        ),
    ]
