# Generated by Django 4.0 on 2022-10-29 14:11

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='Путь')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdeaStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=255, verbose_name='Старый статус')),
                ('new_status', models.CharField(max_length=255, verbose_name='Новый Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'История статусов идеи',
                'verbose_name_plural': 'История статусов идей',
            },
        ),
        migrations.RemoveField(
            model_name='ideadocuments',
            name='idea',
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_json',
            field=models.JSONField(blank=True, null=True, verbose_name='JSON идеи'),
        ),
        migrations.AddConstraint(
            model_name='ideacomment',
            constraint=models.CheckConstraint(check=models.Q(('parent', django.db.models.expressions.F('id')), _negated=True), name='parent_row_not_equal_to_self'),
        ),
        migrations.DeleteModel(
            name='IdeaDocuments',
        ),
        migrations.AddField(
            model_name='ideastatushistory',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.idea', verbose_name='Идея'),
        ),
        migrations.AddField(
            model_name='ideadocument',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ideas.idea', verbose_name='Идея'),
        ),
    ]
