# Generated by Django 4.0 on 2022-10-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_ideadocument_ideastatushistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideatag',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
