# Generated by Django 4.0 on 2022-10-30 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_alter_idea_category_alter_idea_subscribers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideacomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ideas.ideacomment', verbose_name='Родительский комментарий'),
        ),
    ]
