# Generated by Django 4.0 on 2022-10-31 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_alter_ideacomment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlike',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лайк поста', 'verbose_name_plural': 'Лайки постов'},
        ),
        migrations.AlterField(
            model_name='ideainformation',
            name='idea',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='information', to='ideas.idea', verbose_name='Идея'),
        ),
        migrations.AlterField(
            model_name='ideasettings',
            name='idea',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='ideas.idea', verbose_name='Идея'),
        ),
    ]
