# Generated by Django 4.0 on 2022-11-01 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_alter_postlike_options_alter_ideainformation_idea_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ideacomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий к идеи', 'verbose_name_plural': 'Комментарии к идеям'},
        ),
    ]
