# Generated by Django 4.0 on 2022-11-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_alter_ideacomment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideasettings',
            name='is_joinable',
        ),
        migrations.AddField(
            model_name='post',
            name='post_json',
            field=models.JSONField(blank=True, null=True, verbose_name='JSON поста'),
        ),
    ]
