# Generated by Django 4.0 on 2022-11-04 10:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_interest_chat'),
        ('ideas', '0008_remove_ideasettings_is_joinable_post_post_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='Путь')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ideas.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Документ поста',
                'verbose_name_plural': 'Документы постов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='IdeaTag',
        ),
        migrations.AlterField(
            model_name='idea',
            name='tags',
            field=models.ManyToManyField(blank=True, to='users.Interest', verbose_name='Теги'),
        ),
    ]
