# Generated by Django 4.0 on 2022-11-04 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0010_post_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='ideas.idea', verbose_name='Идея'),
        ),
    ]
