# Generated by Django 4.0 on 2022-11-05 02:47

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0012_alter_postcomment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ideainformation',
            options={},
        ),
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('on_moderation', 'На модерации'), ('need_work', 'Нуждается в доработке'), ('cancelled', 'Отклонена'), ('approved', 'Одобрена'), ('finished', 'Завершена')], default='created', max_length=255, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='postcomment',
            constraint=models.CheckConstraint(check=models.Q(('parent', django.db.models.expressions.F('id')), _negated=True), name='parent_row_not_equal_to_self_posts'),
        ),
    ]
