# Generated by Django 4.0 on 2022-11-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_chatnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatnotification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
    ]
