# Generated by Django 4.0 on 2022-11-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_chatnotification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название чата'),
        ),
    ]
