# Generated by Django 4.0 on 2022-11-05 22:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_country_country_code'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID Метрики')),
                ('method', models.CharField(max_length=255, verbose_name='Метод')),
                ('request_path', models.CharField(max_length=255, verbose_name='Путь')),
                ('status_code', models.IntegerField(verbose_name='Код ответа')),
                ('remote_address', models.CharField(max_length=255, verbose_name='IP адрес')),
                ('taken_time', models.FloatField(verbose_name='Время выполнения запроса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Метрика',
                'verbose_name_plural': 'Метрики',
            },
        ),
    ]
